version: "3.9"
services:
  api:
    image: shoutitbot/api:latest
    networks:
      - shoutit-internal
      - shoutit-external

  app:
    image: shoutitbot/app:latest
    networks:
      - shoutit-internal
      - shoutit-external
